# Generated by Django 6.0.4 on 2026-05-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('adult', 'Adulte'), ('pregnant', 'Grossesse'), ('child', 'Enfant'), ('sensitive_skin', 'Peau sensible'), ('athlete', 'Sportif'), ('other', 'Autre'), ('asthma', 'Asthma'), ('diabetes', 'Diabetes'), ('newborn', 'Newborn'), ('fetal', 'Fetal'), ('cardiovascular', 'Cardiovascular'), ('pcos', 'PCOS')], max_length=32),
        ),
    ]
